/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AdopterService } from "../adopter.service";
import { AdopterCreateInput } from "./AdopterCreateInput";
import { AdopterWhereInput } from "./AdopterWhereInput";
import { AdopterWhereUniqueInput } from "./AdopterWhereUniqueInput";
import { AdopterFindManyArgs } from "./AdopterFindManyArgs";
import { AdopterUpdateInput } from "./AdopterUpdateInput";
import { Adopter } from "./Adopter";
import { RescueFindManyArgs } from "../../rescue/base/RescueFindManyArgs";
import { Rescue } from "../../rescue/base/Rescue";
import { RescueWhereUniqueInput } from "../../rescue/base/RescueWhereUniqueInput";

export class AdopterControllerBase {
  constructor(protected readonly service: AdopterService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Adopter })
  async create(@common.Body() data: AdopterCreateInput): Promise<Adopter> {
    return await this.service.create({
      data: data,
      select: {
        email: true,
        id: true,
        name: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Adopter] })
  @ApiNestedQuery(AdopterFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Adopter[]> {
    const args = plainToClass(AdopterFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        email: true,
        id: true,
        name: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Adopter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: AdopterWhereUniqueInput
  ): Promise<Adopter | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        email: true,
        id: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Adopter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: AdopterWhereUniqueInput,
    @common.Body() data: AdopterUpdateInput
  ): Promise<Adopter | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          email: true,
          id: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Adopter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: AdopterWhereUniqueInput
  ): Promise<Adopter | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          email: true,
          id: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/pets")
  @ApiNestedQuery(RescueFindManyArgs)
  async findManyPets(
    @common.Req() request: Request,
    @common.Param() params: AdopterWhereUniqueInput
  ): Promise<Rescue[]> {
    const query = plainToClass(RescueFindManyArgs, request.query);
    const results = await this.service.findPets(params.id, {
      ...query,
      select: {
        adopter: {
          select: {
            id: true,
          },
        },

        age: true,
        id: true,
        name: true,
        species: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/pets")
  async connectPets(
    @common.Param() params: AdopterWhereUniqueInput,
    @common.Body() body: RescueWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pets: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/pets")
  async updatePets(
    @common.Param() params: AdopterWhereUniqueInput,
    @common.Body() body: RescueWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pets: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/pets")
  async disconnectPets(
    @common.Param() params: AdopterWhereUniqueInput,
    @common.Body() body: RescueWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pets: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
